services:
  jenkins:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"

    volumes:
      - jenkins_home:/var/jenkins_home
      - ./Oracle_Cloud_Infrastructure/oci-server:/terraform
      - ./Oracle_Cloud_Infrastructure/.oci:/home/jenkins/.oci
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home: